<?php
Kirki::add_section( 'header_layout', array(
    'priority'    => 1,
    'title'       => esc_html__( 'Header Layout', 'amino' ),
    'panel'       => 'header',
) );
Kirki::add_field( 'option', [
	'type'        => 'radio-image',
	'settings'    => 'header_layout',
	'label'       => esc_html__( 'Select header layout', 'amino' ),
	'section'     => 'header_layout',
	'default'     => '1',
	'choices'     => [
		'1'   => get_template_directory_uri() . '/assets/images/customizer/header1.jpg',
		'2' => get_template_directory_uri() . '/assets/images/customizer/header2.jpg',
		'3'  => get_template_directory_uri() . '/assets/images/customizer/header3.jpg',
		'4'  => get_template_directory_uri() . '/assets/images/customizer/header4.jpg',
	],
	'preset'      => array(
		'1'    => array(
			'settings' => array(
				'header_promo_active' => true,
				'header_promo_close' => true,
				'header_promo_bground' => '#1d1d1d',
				'header_topbar_active' => false,
				'header_main_padding' => 18,
				'header_search_layout' => 'search-sidebar',
				'he_account_design' => 'only-icon',
				'header_elements_cart_icon' => 'bag2',
				'header_elements_cart_minicart' => 'off-canvas',
				'header_main_background' => ['background-color' => '#ffffff'],
				'header_main_text' => 'dark',
				'hmenu_background' => 'rgba(255,255,255,0)',
				'hmenu_item_align' => 'center',
				'hmenu_item_color' => '#1d1d1d',
				'hmenu_item_color_active' => '#83bc2e',
				'hmenu_item_background_color' => 'rgba(255,255,255,0)',
				'hmenu_item_background_color_active' => 'rgba(255,255,255,0)',
				'hmenu_item_font' => '14',
				'hmenu_item_space' => '18',
				'vertical_menu_active' => false,
				
			),
		),
		'2'   => array(
			'settings' => array(
				'header_promo_active' => false,
				'header_promo_close' => true,
				'header_promo_bground' => '#1d1d1d',
				'header_topbar_active' => false,
				'header_main_padding' => 18,
				'header_search_layout' => 'search-simple2',
				'header_search_submit' => 'text',
				'he_account_design' => 'only-icon',
				'header_elements_cart_icon' => 'bag2',
				'header_elements_cart_minicart' => 'off-canvas',
				'header_main_background' => ['background-color' => '#ffffff'],
				'header_main_text' => 'dark',
				'hmenu_item_color' => '#ffffff',
				'header_search_textsubmit' => 'Search',
				'hmenu_background' => 'rgba(255,255,255,0)',
				'hmenu_item_align' => 'center',
				'hmenu_item_color_active' => '#83bc2e',
				'hmenu_item_background_color' => 'rgba(255,255,255,0)',
				'hmenu_item_background_color_active' => 'rgba(255,255,255,0)',
				'hmenu_item_font' => '14',
				'hmenu_item_space' => '18',
				'vertical_menu_active' => true,
			),
		),
		'3' => [
			'settings' => [
				'header_promo_active' => false,
				'header_promo_bground' => '#1d1d1d',
				'header_topbar_active' => true,
				'header_topbar_background' => '#1d1d1d',
				'header_topbar_text' => 'light',
				'topbar_left' => array(
					0 => ['block' => 'notice'],
				),
				'topbar_right' => array(
					0 => ['block' => 'language'],
					1 => ['block' => 'currency']
				),
				'header_main_padding' => 18,
				'header_search_layout' => 'search-sidebar',
				'he_account_design' => 'only-icon',
				'header_elements_cart_icon' => 'bag2',
				'header_elements_cart_minicart' => 'off-canvas',
				'header_main_background' => ['background-color' => '#ffffff'],
				'header_main_text' => 'dark',
				'hmenu_background' => 'rgba(255,255,255,0)',
				'hmenu_item_align' => 'center',
				'hmenu_item_color' => '#1d1d1d',
				'hmenu_item_color_active' => '#83bc2e',
				'hmenu_item_background_color' => 'rgba(255,255,255,0)',
				'hmenu_item_background_color_active' => 'rgba(255,255,255,0)',
				'hmenu_item_font' => '14',
				'hmenu_item_space' => '18',
				'vertical_menu_active' => false,
			],
		],
		'4'    => array(
			'settings' => array(
				'header_promo_active' => false,
				'header_promo_bground' => '#1d1d1d',
				'header_topbar_active' => true,
				'header_topbar_background' => '#ffffff',
				'header_topbar_text' => 'dark',
				'topbar_left' => array(
					0 => ['block' => 'notice'],
				),
				'topbar_right' => array(
					0 => ['block' => 'language'],
					1 => ['block' => 'currency']
				),
				'header_main_padding' => 18,
				'header_search_layout' => 'search-sidebar',
				'he_account_design' => 'only-icon',
				'header_elements_cart_icon' => 'bag2',
				'header_elements_cart_minicart' => 'off-canvas',
				'header_main_background' => ['background-color' => '#ffffff'],
				'header_main_text' => 'dark',
				'hmenu_background' => 'rgba(255,255,255,0)',
				'hmenu_item_align' => 'center',
				'hmenu_item_color' => '#1d1d1d',
				'hmenu_item_color_active' => '#83bc2e',
				'hmenu_item_background_color' => 'rgba(255,255,255,0)',
				'hmenu_item_background_color_active' => 'rgba(255,255,255,0)',
				'hmenu_item_font' => '14',
				'hmenu_item_space' => '18',
				'vertical_menu_active' => false,
			),
		),
	),
] );